language: node_js
node_js:
  - "12.16.3"
dist: trusty
sudo: required
cache:
    directories:
      - node_modules

branches:
  only:
  - master

before_install:
  - export TZ='Asia/Shanghai'
install:
  - npm install hexo-cli@3.1.0 -g
  - npm install


script:
  - hexo clean
  - hexo generate

after_script:
  - cd ./public
  - git init
  - git config user.name "mxcall"
  - git config user.email "515324060@qq.com"
  - git add .
  - git commit -m "Travis CI Auto Builder at $(date +'%Y-%m-%d %H:%M:%S')"
  - git push --force --quiet "https://${GIT_REPO_TOKEN}@${GIT_REPO_REF}" master:master
  - git push --force  "https://${GEE_REPO_TOKEN}@${GEE_REPO_REF}" master:master


notifications:
  email: true